import AsyncStorage from "@react-native-async-storage/async-storage";
import { nokRegistrationURL } from "../constants/api_constants";

export const editProfile = async ({
  isUpdate,
  aadharCardFront,
  aadharCardBack,
  panCardImage,
  addressProof,
  firstName,
  lastName,
  email,
  mobileNumber,
  serviceNumber,
  headquarters,
  rank,
  dateOfBirth,
  dateOfEnrollment,
  dateOfDeath,
  isGalantry,
  isPension,
  ppoNo,
  bankName,
  accountNumber,
  echsCardNo,
  nokName,
  dateOfNok,
  relationShip,
  adharCardNumber,
  panCard,
  pensionUid,
  domicile,
  address,
  city,
  state,
  pinCode,
  postOfficeCode,
}) => {};
